title: paola chiara masuzzo
description: a space in the word wide web to make sure something stays
url: "https://pcmasuzzo.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima

# Social links (optional)
github_username: pcmasuzzo
