name: Auto-generate gallery

on:
  push:
    branches:
      - main
    paths:
      - 'assets/**'           # trigger only if any file in assets/ changes
      - 'scripts/igotup_gallery.py'  # also trigger if the Python script changes

jobs:
  build-gallery:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allows pushing back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run gallery generator
        run: python scripts/igotup_gallery.py

      - name: Commit and push updated gallery
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _includes/igotup_gallery.html
          git commit -m "Auto-update gallery" || echo "No changes to commit"
          git push
